# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECE530/project/Zybo-Z7-20-HDMI-v2018.2-2_w_xpr/hdmi_demo_changed_for_testing/hdmi_demo_changed_for_testing.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
# IP: The module: 'design_1_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE530/project/Zybo-Z7-20-HDMI-v2018.2-2_w_xpr/hdmi_demo_changed_for_testing/hdmi_demo_changed_for_testing.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/ECE530/project/Zybo-Z7-20-HDMI-v2018.2-2_w_xpr/hdmi_demo_changed_for_testing/hdmi_demo_changed_for_testing.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
# IP: The module: 'design_1_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE530/project/Zybo-Z7-20-HDMI-v2018.2-2_w_xpr/hdmi_demo_changed_for_testing/hdmi_demo_changed_for_testing.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
